// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vucfaxjhxuvwswwytbwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1Y2ZheGpoeHV2d3N3d3l0Ynd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2ODc2MjEsImV4cCI6MjA3NzI2MzYyMX0.dmsoDCjAjwFaC7EN_E38ftC_3gKet0Vh3HIyEaFAhl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);